#!/bin/bash

# add user to PostgreSQL
adduser swa

# admin stuff
mkdir /usr/local/pgsql/data
chown postgres /usr/local/pgsql/data
su - postgres

# to create the database
/usr/local/pgsql/bin/initdb   -D /usr/local/pgsql/data
/usr/local/pgsql/bin/postgres -D /usr/local/pgsql/data >logfile 2>&1 &
/usr/local/pgsql/bin/createdb test
/usr/local/pgsql/bin/psql     test
