package at.ac.tuwien.swag.model.domain.quartz;

// Generated Jun 11, 2011 5:07:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * QrtzFiredTriggers generated by hbm2java
 */
@Entity
@Table(name = "qrtz_fired_triggers", schema = "public")
public class QrtzFiredTriggers implements java.io.Serializable {

	private QrtzFiredTriggersId id;
	private String triggerName;
	private String triggerGroup;
	private String instanceName;
	private long firedTime;
	private int priority;
	private String state;
	private String jobName;
	private String jobGroup;
	private Boolean isNonconcurrent;
	private Boolean requestsRecovery;

	public QrtzFiredTriggers() {
	}

	public QrtzFiredTriggers( QrtzFiredTriggersId id, String triggerName,
			String triggerGroup, String instanceName, long firedTime,
			int priority, String state ) {
		this.id = id;
		this.triggerName = triggerName;
		this.triggerGroup = triggerGroup;
		this.instanceName = instanceName;
		this.firedTime = firedTime;
		this.priority = priority;
		this.state = state;
	}

	public QrtzFiredTriggers( QrtzFiredTriggersId id, String triggerName,
			String triggerGroup, String instanceName, long firedTime,
			int priority, String state, String jobName, String jobGroup,
			Boolean isNonconcurrent, Boolean requestsRecovery ) {
		this.id = id;
		this.triggerName = triggerName;
		this.triggerGroup = triggerGroup;
		this.instanceName = instanceName;
		this.firedTime = firedTime;
		this.priority = priority;
		this.state = state;
		this.jobName = jobName;
		this.jobGroup = jobGroup;
		this.isNonconcurrent = isNonconcurrent;
		this.requestsRecovery = requestsRecovery;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "schedName", column = @Column(name = "sched_name", nullable = false, length = 120)),
			@AttributeOverride(name = "entryId", column = @Column(name = "entry_id", nullable = false, length = 95)) })
	public QrtzFiredTriggersId getId() {
		return this.id;
	}

	public void setId( QrtzFiredTriggersId id ) {
		this.id = id;
	}

	@Column(name = "trigger_name", nullable = false, length = 200)
	public String getTriggerName() {
		return this.triggerName;
	}

	public void setTriggerName( String triggerName ) {
		this.triggerName = triggerName;
	}

	@Column(name = "trigger_group", nullable = false, length = 200)
	public String getTriggerGroup() {
		return this.triggerGroup;
	}

	public void setTriggerGroup( String triggerGroup ) {
		this.triggerGroup = triggerGroup;
	}

	@Column(name = "instance_name", nullable = false, length = 200)
	public String getInstanceName() {
		return this.instanceName;
	}

	public void setInstanceName( String instanceName ) {
		this.instanceName = instanceName;
	}

	@Column(name = "fired_time", nullable = false)
	public long getFiredTime() {
		return this.firedTime;
	}

	public void setFiredTime( long firedTime ) {
		this.firedTime = firedTime;
	}

	@Column(name = "priority", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority( int priority ) {
		this.priority = priority;
	}

	@Column(name = "state", nullable = false, length = 16)
	public String getState() {
		return this.state;
	}

	public void setState( String state ) {
		this.state = state;
	}

	@Column(name = "job_name", length = 200)
	public String getJobName() {
		return this.jobName;
	}

	public void setJobName( String jobName ) {
		this.jobName = jobName;
	}

	@Column(name = "job_group", length = 200)
	public String getJobGroup() {
		return this.jobGroup;
	}

	public void setJobGroup( String jobGroup ) {
		this.jobGroup = jobGroup;
	}

	@Column(name = "is_nonconcurrent")
	public Boolean getIsNonconcurrent() {
		return this.isNonconcurrent;
	}

	public void setIsNonconcurrent( Boolean isNonconcurrent ) {
		this.isNonconcurrent = isNonconcurrent;
	}

	@Column(name = "requests_recovery")
	public Boolean getRequestsRecovery() {
		return this.requestsRecovery;
	}

	public void setRequestsRecovery( Boolean requestsRecovery ) {
		this.requestsRecovery = requestsRecovery;
	}

}
