package at.ac.tuwien.swag.model.domain.quartz;

// Generated Jun 11, 2011 5:07:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * QrtzBlobTriggers generated by hbm2java
 */
@Entity
@Table(name = "qrtz_blob_triggers", schema = "public")
public class QrtzBlobTriggers implements java.io.Serializable {

	private QrtzBlobTriggersId id;
	private QrtzTriggers qrtzTriggers;
	private byte[] blobData;

	public QrtzBlobTriggers() {
	}

	public QrtzBlobTriggers( QrtzTriggers qrtzTriggers ) {
		this.qrtzTriggers = qrtzTriggers;
	}

	public QrtzBlobTriggers( QrtzTriggers qrtzTriggers, byte[] blobData ) {
		this.qrtzTriggers = qrtzTriggers;
		this.blobData = blobData;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "schedName", column = @Column(name = "sched_name", nullable = false, length = 120)),
			@AttributeOverride(name = "triggerName", column = @Column(name = "trigger_name", nullable = false, length = 200)),
			@AttributeOverride(name = "triggerGroup", column = @Column(name = "trigger_group", nullable = false, length = 200)) })
	public QrtzBlobTriggersId getId() {
		return this.id;
	}

	public void setId( QrtzBlobTriggersId id ) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public QrtzTriggers getQrtzTriggers() {
		return this.qrtzTriggers;
	}

	public void setQrtzTriggers( QrtzTriggers qrtzTriggers ) {
		this.qrtzTriggers = qrtzTriggers;
	}

	@Column(name = "blob_data")
	public byte[] getBlobData() {
		return this.blobData;
	}

	public void setBlobData( byte[] blobData ) {
		this.blobData = blobData;
	}

}
