package at.ac.tuwien.swag.model.domain.quartz;

// Generated Jun 11, 2011 5:07:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * QrtzSchedulerState generated by hbm2java
 */
@Entity
@Table(name = "qrtz_scheduler_state", schema = "public")
public class QrtzSchedulerState implements java.io.Serializable {

	private QrtzSchedulerStateId id;
	private long lastCheckinTime;
	private long checkinInterval;

	public QrtzSchedulerState() {
	}

	public QrtzSchedulerState( QrtzSchedulerStateId id, long lastCheckinTime,
			long checkinInterval ) {
		this.id = id;
		this.lastCheckinTime = lastCheckinTime;
		this.checkinInterval = checkinInterval;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "schedName", column = @Column(name = "sched_name", nullable = false, length = 120)),
			@AttributeOverride(name = "instanceName", column = @Column(name = "instance_name", nullable = false, length = 200)) })
	public QrtzSchedulerStateId getId() {
		return this.id;
	}

	public void setId( QrtzSchedulerStateId id ) {
		this.id = id;
	}

	@Column(name = "last_checkin_time", nullable = false)
	public long getLastCheckinTime() {
		return this.lastCheckinTime;
	}

	public void setLastCheckinTime( long lastCheckinTime ) {
		this.lastCheckinTime = lastCheckinTime;
	}

	@Column(name = "checkin_interval", nullable = false)
	public long getCheckinInterval() {
		return this.checkinInterval;
	}

	public void setCheckinInterval( long checkinInterval ) {
		this.checkinInterval = checkinInterval;
	}

}
