package at.ac.tuwien.swag.model.domain.quartz;

// Generated Jun 11, 2011 5:07:29 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * QrtzSimpropTriggers generated by hbm2java
 */
@Entity
@Table(name = "qrtz_simprop_triggers", schema = "public")
public class QrtzSimpropTriggers implements java.io.Serializable {

	private QrtzSimpropTriggersId id;
	private QrtzTriggers qrtzTriggers;
	private String strProp1;
	private String strProp2;
	private String strProp3;
	private Integer intProp1;
	private Integer intProp2;
	private Long longProp1;
	private Long longProp2;
	private BigDecimal decProp1;
	private BigDecimal decProp2;
	private Boolean boolProp1;
	private Boolean boolProp2;

	public QrtzSimpropTriggers() {
	}

	public QrtzSimpropTriggers( QrtzTriggers qrtzTriggers ) {
		this.qrtzTriggers = qrtzTriggers;
	}

	public QrtzSimpropTriggers( QrtzTriggers qrtzTriggers, String strProp1,
			String strProp2, String strProp3, Integer intProp1,
			Integer intProp2, Long longProp1, Long longProp2,
			BigDecimal decProp1, BigDecimal decProp2, Boolean boolProp1,
			Boolean boolProp2 ) {
		this.qrtzTriggers = qrtzTriggers;
		this.strProp1 = strProp1;
		this.strProp2 = strProp2;
		this.strProp3 = strProp3;
		this.intProp1 = intProp1;
		this.intProp2 = intProp2;
		this.longProp1 = longProp1;
		this.longProp2 = longProp2;
		this.decProp1 = decProp1;
		this.decProp2 = decProp2;
		this.boolProp1 = boolProp1;
		this.boolProp2 = boolProp2;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "schedName", column = @Column(name = "sched_name", nullable = false, length = 120)),
			@AttributeOverride(name = "triggerName", column = @Column(name = "trigger_name", nullable = false, length = 200)),
			@AttributeOverride(name = "triggerGroup", column = @Column(name = "trigger_group", nullable = false, length = 200)) })
	public QrtzSimpropTriggersId getId() {
		return this.id;
	}

	public void setId( QrtzSimpropTriggersId id ) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public QrtzTriggers getQrtzTriggers() {
		return this.qrtzTriggers;
	}

	public void setQrtzTriggers( QrtzTriggers qrtzTriggers ) {
		this.qrtzTriggers = qrtzTriggers;
	}

	@Column(name = "str_prop_1", length = 512)
	public String getStrProp1() {
		return this.strProp1;
	}

	public void setStrProp1( String strProp1 ) {
		this.strProp1 = strProp1;
	}

	@Column(name = "str_prop_2", length = 512)
	public String getStrProp2() {
		return this.strProp2;
	}

	public void setStrProp2( String strProp2 ) {
		this.strProp2 = strProp2;
	}

	@Column(name = "str_prop_3", length = 512)
	public String getStrProp3() {
		return this.strProp3;
	}

	public void setStrProp3( String strProp3 ) {
		this.strProp3 = strProp3;
	}

	@Column(name = "int_prop_1")
	public Integer getIntProp1() {
		return this.intProp1;
	}

	public void setIntProp1( Integer intProp1 ) {
		this.intProp1 = intProp1;
	}

	@Column(name = "int_prop_2")
	public Integer getIntProp2() {
		return this.intProp2;
	}

	public void setIntProp2( Integer intProp2 ) {
		this.intProp2 = intProp2;
	}

	@Column(name = "long_prop_1")
	public Long getLongProp1() {
		return this.longProp1;
	}

	public void setLongProp1( Long longProp1 ) {
		this.longProp1 = longProp1;
	}

	@Column(name = "long_prop_2")
	public Long getLongProp2() {
		return this.longProp2;
	}

	public void setLongProp2( Long longProp2 ) {
		this.longProp2 = longProp2;
	}

	@Column(name = "dec_prop_1", precision = 13, scale = 4)
	public BigDecimal getDecProp1() {
		return this.decProp1;
	}

	public void setDecProp1( BigDecimal decProp1 ) {
		this.decProp1 = decProp1;
	}

	@Column(name = "dec_prop_2", precision = 13, scale = 4)
	public BigDecimal getDecProp2() {
		return this.decProp2;
	}

	public void setDecProp2( BigDecimal decProp2 ) {
		this.decProp2 = decProp2;
	}

	@Column(name = "bool_prop_1")
	public Boolean getBoolProp1() {
		return this.boolProp1;
	}

	public void setBoolProp1( Boolean boolProp1 ) {
		this.boolProp1 = boolProp1;
	}

	@Column(name = "bool_prop_2")
	public Boolean getBoolProp2() {
		return this.boolProp2;
	}

	public void setBoolProp2( Boolean boolProp2 ) {
		this.boolProp2 = boolProp2;
	}

}
