package at.ac.tuwien.swag.model.domain.quartz;

// Generated Jun 11, 2011 5:07:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * QrtzLocks generated by hbm2java
 */
@Entity
@Table(name = "qrtz_locks", schema = "public")
public class QrtzLocks implements java.io.Serializable {

	private QrtzLocksId id;

	public QrtzLocks() {
	}

	public QrtzLocks( QrtzLocksId id ) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "schedName", column = @Column(name = "sched_name", nullable = false, length = 120)),
			@AttributeOverride(name = "lockName", column = @Column(name = "lock_name", nullable = false, length = 40)) })
	public QrtzLocksId getId() {
		return this.id;
	}

	public void setId( QrtzLocksId id ) {
		this.id = id;
	}

}
