package at.ac.tuwien.swag.model.domain.quartz;

// Generated Jun 11, 2011 5:07:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * QrtzPausedTriggerGrps generated by hbm2java
 */
@Entity
@Table(name = "qrtz_paused_trigger_grps", schema = "public")
public class QrtzPausedTriggerGrps implements java.io.Serializable {

	private QrtzPausedTriggerGrpsId id;

	public QrtzPausedTriggerGrps() {
	}

	public QrtzPausedTriggerGrps( QrtzPausedTriggerGrpsId id ) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "schedName", column = @Column(name = "sched_name", nullable = false, length = 120)),
			@AttributeOverride(name = "triggerGroup", column = @Column(name = "trigger_group", nullable = false, length = 200)) })
	public QrtzPausedTriggerGrpsId getId() {
		return this.id;
	}

	public void setId( QrtzPausedTriggerGrpsId id ) {
		this.id = id;
	}

}
